ClinicSystem/Areas/Admin/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClinicSystem.Areas.Admin.Controllers
{
    public class GroupsController : Controller
    {
        // GET: Admin/Groups
        public ActionResult Groups()
        {
            return View();
        }
        public ActionResult NewGroups()
        {
            return View();
        }
    }
}

ClinicSystem/Areas/Admin/Controllers/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using DataAccessClinicSystem.Entity;
using System.Net.Http;
using Newtonsoft.Json;

namespace ClinicSystem.Areas.Admin.Controllers
{
    public class ModuleController : Controller
    {
        // GET: Admin/Module
        public async Task<ActionResult> ModuleList()
        {
            VMmodule vm = new VMmodule();
            List<Module> moduleList = new List<Module>();
            string ApiUrl = "http://localhost/ClinicSystemApi/api/Module/MainMoudle";
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(ApiUrl);
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage responseMessage = await client.GetAsync(ApiUrl);
            if(responseMessage.IsSuccessStatusCode)
            {
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;
                moduleList = JsonConvert.DeserializeObject<List<Module>>(responseData);
            }
            vm.Mod = moduleList;
            return View("ModuleList",vm);
        }
        public ActionResult Update(int id)
        {
            ViewData["Id"] = id;
            return View("NewModule");
        }
        public ActionResult NewModule()
        {
            return View();
        }
    }
}

ClinicSystem/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClinicSystem.Areas.Admin.Controllers
{
    public class UserController : Controller
    {
        // GET: Admin/User
        public ActionResult Users()
        {
            return View();
        }
        public ActionResult NewUsers()
        {
            return View();
        }
    }
}

ClinicSystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClinicSystem.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ClinicSystem/Areas/Admin/Views/Groups/Groups.cshtml
@{
    ViewBag.Title = "Groups";
    Layout = "~/Views/Shared/HomePage.cshtml";
}

@section Body{
<div class="x_panel">
    <div class="row">
        <div class="col-lg-3">
            <h2 style="color:#0094ff">Groups</h2>
        </div>
        <div class="col-lg-2 col-lg-offset-7">
            <button style="font-size:xx-large" class="btn btn-lg">
                <span style="color:#0094ff" class="fa fa-plus-square"></span>
            </button>
        </div>
    </div>
    <div class="x_title"></div>
    <div class="form-group">
        <div class="row">
            <div class="col-lg-1">
                <input type="checkbox" name="checed" />
            </div>
            <div class="col-lg-4">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-search"></i></span>
                    <input id="txtSearch" type="text" class="form-control" name="txtSearch" placeholder="Search...">
                </div>
            </div>
            <div class="col-lg-4">
                <button type="button" class="btn border-primary">
                    <span class="fa fa-search"></span> Search
                </button>
            </div>
        </div>
    </div>
    <br />
    <br />
    <div class="x_title"></div>
    <div class="row">
        <div class="col-lg-1">
            <input type="checkbox" name="checed" />
        </div>
        <div class="col-lg-5">
            <h4 style="color:#808080">Group Name : Administrator</h4>
            <h5 style="color:#808080">Status: Active</h5>
        </div>
        <div class="col-lg-4 col-lg-offset-2">
            <div class="btn-group" role="group" aria-label="Basic example">
                <button type="button" class="btn btn-dark">
                    <span class="fa fa-edit"></span> Edit
                </button>
                <button type="button" class="btn btn-default">
                    <span class="fa fa-trash"></span> delete
                </button>
                <button type="button" class="btn btn-danger">
                    <span class="fa fa-plus"></span> Change Status
                </button>
            </div>
        </div>
    </div>
    <div class="x_title"></div>
    <div class="row">
        <div class="col-lg-1">
            <input type="checkbox" name="checed" />
        </div>
        <div class="col-lg-5">
            <h4 style="color:#808080">Group Name : Reception</h4>
            <h5 style="color:#808080">Status: Active</h5>
        </div>
        <div class="col-lg-4 col-lg-offset-2">
            <div class="btn-group" role="group" aria-label="Basic example">
                <button type="button" class="btn btn-dark">
                    <span class="fa fa-edit"></span> Edit
                </button>
                <button type="button" class="btn btn-default">
                    <span class="fa fa-trash"></span> delete
                </button>
                <button type="button" class="btn btn-danger">
                    <span class="fa fa-plus"></span> Change Status
                </button>
            </div>
        </div>
    </div>
    <div class="x_title"></div>
    <div class="row">
        <div class="col-lg-1">
            <input type="checkbox" name="checed" />
        </div>
        <div class="col-lg-5">
            <h4 style="color:#808080">Group Name : Doctor</h4>
            <h5 style="color:#808080">Status: Active</h5>
        </div>
        <div class="col-lg-4 col-lg-offset-2">
            <div class="btn-group" role="group" aria-label="Basic example">
                <button type="button" class="btn btn-dark">
                    <span class="fa fa-edit"></span> Edit
                </button>
                <button type="button" class="btn btn-default">
                    <span class="fa fa-trash"></span> delete
                </button>
                <button type="button" class="btn btn-danger">
                    <span class="fa fa-plus"></span> Change Status
                </button>
            </div>
        </div>
    </div>
</div>
    }

ClinicSystem/Areas/Admin/Views/Groups/NewGroups.cshtml
@{
    ViewBag.Title = "NewGroups";
    Layout = "~/Views/Shared/HomePage.cshtml";
}
@section Body{
    <div class="container x_panel">
        <div class="row">
            <div class="col-lg-3">
                <h4 style="color:#18cce5">New Group</h4>
            </div>
            <div class="col-lg-2 col-lg-offset-5">
                <button type="button" class="btn btn-outline-success">
                    <span class="fa fa-save"></span> Save
                </button>
            </div>
            <div class="col-lg-2">
                <button type="button" class="btn btn-outline-danger">
                    <span class="fa fa-trash"></span> Discared
                </button>
            </div>
        </div>
        <div class="x_title"></div>
        <div class="x_panel">
            <h4 style="color:#808080">Group Information</h4>
            <div class="x_title"></div>
            <div class="container-fluid">
                <div class="form-group">
                    <div class="row justify-content-center">
                        <div class="col-lg-2">
                            <label>Name :</label>
                        </div>
                        <div class="col-lg-5">
                            <input type="text" class="form-control" name="txtname" />
                        </div>
                    </div>
                    <div class="x_content"></div>
                    <div class="row justify-content-center">
                        <div class="col-lg-2">
                            <label>Short name :</label>
                        </div>
                        <div class="col-lg-5">
                            <input type="text" class="form-control" name="txtShname" />
                        </div>
                    </div>
                    <div class="x_content"></div>
                    <div class="row justify-content-center">
                        <div class="col-lg-2">
                            <label>Status :</label>
                        </div>
                        <div class="col-lg-5">
                            <input type="checkbox" name="txtorder" value="Active" />
                            <label>Active</label>
                        </div>
                    </div>
                    <div class="x_content"></div>
                    <div class="row justify-content-center">
                        <div class="col-lg-2">
                            <label>Status Date :</label>
                        </div>
                        <div class="col-lg-5">
                            <input type="datetime-local" class="form-control" name="txtDate" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container x_panel">
        <div class="row justify-content-center">
            <div class="col-lg-4">
                <p>Pages</p>
                <table class="table" border="1">
                    <thead style="background-color:#291ebf;color:white">
                        <tr>
                            <th>
                                <input type="checkbox" name="checkall" />
                            </th>
                            <th>
                                <p>Page Name</p>
                            </th>
                            <th>
                                <p>Page Order</p>
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <input type="checkbox" name="check" />
                            </td>
                            <td>
                                <p>PatintList</p>
                            </td>
                            <td>
                                <p>1</p>
                            </td>
                            <td>
                                <button class="btn">
                                    <span class="fa fa-plus-circle"></span>
                                </button>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="checkbox" name="check" />
                            </td>
                            <td>
                                <p>PatintList</p>
                            </td>
                            <td>
                                <p>1</p>
                            </td>
                            <td>
                                <button class="btn">
                                    <span class="fa fa-plus-circle"></span>
                                </button>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="checkbox" name="check" />
                            </td>
                            <td>
                                <p>PatintList</p>
                            </td>
                            <td>
                                <p>1</p>
                            </td>
                            <td>
                                <button class="btn">
                                    <span class="fa fa-plus-circle"></span>
                                </button>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="checkbox" name="check" />
                            </td>
                            <td>
                                <p>PatintList</p>
                            </td>
                            <td>
                                <p>1</p>
                            </td>
                            <td>
                                <button class="btn">
                                    <span class="fa fa-plus-circle"></span>
                                </button>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="checkbox" name="check" />
                            </td>
                            <td>
                                <p>PatintList</p>
                            </td>
                            <td>
                                <p>1</p>
                            </td>
                            <td>
                                <button class="btn">
                                    <span class="fa fa-plus-circle"></span>
                                </button>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="checkbox" name="check" />
                            </td>
                            <td>
                                <p>PatintList</p>
                            </td>
                            <td>
                                <p>1</p>
                            </td>
                            <td>
                                <button class="btn">
                                    <span class="fa fa-plus-circle"></span>
                                </button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <p>Accessed</p>
                <table class="table" border="1">
                    <thead style="background-color:#291ebf;color:white">
                        <tr>
                            <th>
                                <input type="checkbox" name="checkall" />
                            </th>
                            <th>
                                <p>Page Name</p>
                            </th>
                            <th>
                                <p>Page Order</p>
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <input type="checkbox" name="check" />
                            </td>
                            <td>
                                <p>PatintList</p>
                            </td>
                            <td>
                                <p>1</p>
                            </td>
                            <td>
                                <button class="btn">
                                    <span style="color:blue" class="fa fa-trash-alt"></span>
                                </button>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="checkbox" name="check" />
                            </td>
                            <td>
                                <p>PatintList</p>
                            </td>
                            <td>
                                <p>1</p>
                            </td>
                            <td>
                                <button class="btn">
                                    <span style="color:blue" class="fa fa-trash-alt"></span>
                                </button>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="checkbox" name="check" />
                            </td>
                            <td>
                                <p>PatintList</p>
                            </td>
                            <td>
                                <p>1</p>
                            </td>
                            <td>
                                <button class="btn">
                                    <span style="color:blue" class="fa fa-trash-alt"></span>
                                </button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}

ClinicSystem/Areas/Admin/Views/Module/ModuleList.cshtml
@model DataAccessClinicSystem.Entity.VMmodule
@{
    ViewBag.Title = "ModuleList";
    Layout = "~/Views/Shared/HomePage.cshtml";
}
@section Head{
    <script type="text/javascript">
        function del(id) {
            debugger;
            $.ajax({
                type: 'post',
                url: '/ClinicSystemApi/api/Module/Deletemod/' + id,
                contentType: 'application/json;charset=utf-8',
                dataType: 'json',
                success: function () {
                    alert("Deleted")
                },
                error: function (error) {
                    alert(error.responseText);
                    alert('there is error');
                }
            });
        }
        function Update(id) {
            debugger;
            window.location = '@Url.Action("Update/Id", "Module")'.replace("Id", id)
        }
    </script>
    }
@section Body{
<div class="x_panel">
    <div class="row">
        <div class="col-lg-3">
            <h2 style="color:#0094ff">Modules List</h2>
        </div>
        <div class="col-lg-2 col-lg-offset-7">
            <button style="font-size:xx-large" class="btn btn-lg">
                <span style="color:#0094ff" class="fa fa-plus-square"></span>
            </button>
        </div>
    </div>
    <div class="x_title"></div>
    <div class="form-group">
        <div class="row">
            <div class="col-lg-1">
                <input type="checkbox" name="checed" />
            </div>
            <div class="col-lg-4">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-search"></i></span>
                    <input id="txtSearch" type="text" class="form-control" name="txtSearch" placeholder="Search...">
                </div>
            </div>
            <div class="col-lg-4">
                <button type="button" class="btn border-primary">
                    <span class="fa fa-search"></span> Search
                </button>
            </div>
        </div>
    </div>
    <br />
    <br />
    <div class="x_title"></div>
    @{
        var m = from a in Model.Mod
                where a.SubModule == 0
                select a;
    }
    @foreach (var x in m)
    {
        <div class="row">
            <div class="col-lg-1">
                <input type="checkbox" name="checed" />
            </div>
            <div class="col-lg-3">
                <h4 style="color:#808080">Moudels Name :@x.Name</h4>
                <h5 style="color:#808080">Oreder: @x.Order</h5>
            </div>
            <div class="col-lg-2 col-lg-offset-4">
                <button type="button" class="btn btn-dark" onclick="Update(@x.Id)">
                    <span class="fa fa-edit"></span> Edit
                </button>
            </div>
            <div class="col-lg-2">
                <button type="button" class="btn btn-default" onclick="del(@x.Id)">
                    <span class="fa fa-trash"></span> delete
                </button>
            </div>
        </div>
       

            <div class="justify-content-center">
                <div style="width:70%;margin-left:15%;margin-right:15%;border: double" class="x_panel">
                    @{var s = from b in Model.Mod
                                where b.SubModule == x.Id
                                select b;
                    }

                    @foreach (var y in s)
                    {
                        <div class="row">
                            <div class="col-lg-5">
                                <h4 style="color:#808080">Sub Module:@y.Name</h4>
                                <h5 style="color:#808080">Oreder:@y.Order</h5>
                            </div>
                            <div class="col-lg-2 col-lg-offset-3">
                                <button type="button" class="btn btn-dark" onclick="Update(@y.Id)">
                                    <span class="fa fa-edit"></span> Edit
                                </button>
                            </div>
                            <div class="col-lg-2">
                                <button type="button" class="btn btn-default" onclick="del(@y.Id)">
                                    <span class="fa fa-trash"></span> delete
                                </button>
                            </div>
                        </div>

                    }
                </div>
            </div>
        
    }
</div>
}

ClinicSystem/Areas/Admin/Views/Module/NewModule.cshtml
@{
    ViewBag.Title = "NewModule";
    Layout = "~/Views/Shared/HomePage.cshtml";
}
@section Head{
    <script src="~/Scripts/NewScripts/jquery-3.3.1.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            debugger;
            $.ajax({
                type: 'Get',
                url: '/ClinicSystemApi/api/Module/SubMoudle',
                contentType: 'application/json;charset=utf-8',
                dataType: 'json',
                data: '{}',
                success: function (data) {
                    $.each(data, function (key, value) {
                        $('#ddlSubmain').append('<option value=' + value.Id + '>' + value.Name + '</option>');
                    });
                },
                error: function (error) {
                    alert(error.responseText);
                    alert('there is error');
                }
            })
            var Id = @ViewData["Id"];
            if (Id != 0) {
                $('#btnSave').text("Update")
                $.ajax({
                    type: 'Get',
                    url: '/ClinicSystemApi/api/Module/Load/' + Id,
                    contentType: 'application/json;charset=utf-8',
                    dataType: 'json',
                    data: '{}',
                    success: function (data) {
                        $('#txtname').val(data.Name);
                        $('#txtorder').val(data.Order);
                        $('#txtpath').val(data.Path);
                        $('#txtShname').val(data.ShortName);
                        $('#ddlSubmain').val(data.SubModule);
                    }
                })
            }
            $('#btnSave').click(function () {
                debugger;
                var Id = @ViewData["Id"];
                if (Id != 0) {
                var name = $("#txtname").val();
                var shortName = $('#txtShname').val();
                var order = $('#txtorder').val();
                var path = $('#txtpath').val();
                var sub = $('#ddlSubmain').val();
                    var data = {
                        'Id': Id,
                    'Name': name,
                    'ShortName': shortName,
                    'Order': order,
                    'Path': path,
                    'SubModule': sub
                }
                    $.ajax({
                        type: 'post',
                        url: '/ClinicSystemApi/api/Module/Update',
                        contentType: 'application/json;charset=utf-8',
                        data: JSON.stringify(data),
                        dataType: 'json',
                        success: function () {
                            alert("Updated")
                        },
                        error: function (error) {
                            alert(error.responseText);
                            alert('there is error');
                        }


                    })
                }
                else {
                    var name = $("#txtname").val();
                    var shortName = $('#txtShname').val();
                    var order = $('#txtorder').val();
                    var path = $('#txtpath').val();
                    var sub = $('#ddlSubmain').val();
                    var data = {
                        'Name': name,
                        'ShortName': shortName,
                        'Order': order,
                        'Path': path,
                        'SubModule': sub
                    }
                    $.ajax({
                        type: 'Post',
                        url: '/ClinicSystemApi/api/Module/Save',
                        contentType: 'application/json;charset=utf-8',
                        data: JSON.stringify(data),
                        dataType: 'json',
                        success: function () {
                            alert("Saved")
                        },
                        error: function (error) {
                            alert(error.responseText);
                            alert('there is error');
                        }


                    })
                }
                
            })
           
        });
    </script>
    
}
@section Body{
    <div class="container x_panel">
        <div class="row">
            <div class="col-lg-3">
                <h4 style="color:#18cce5">New Module</h4>
            </div>
            <div class="col-lg-2 col-lg-offset-5">
                <button type="button" class="btn btn-outline-success" id="btnSave">
                    <span class="fa fa-save"></span> Save
                </button>
            </div>
            <div class="col-lg-2">
                <button type="button" class="btn btn-outline-danger" id="btnUpdate">
                    <span class="fa fa-trash"></span> Discared
                </button>
            </div>
        </div>
        <div class="x_title"></div>
        <div class="x_panel">
            <h4 style="color:#808080">Module Information</h4>
            <div class="x_title"></div>
            <div class="container-fluid">
                <div class="form-group">
                    <div class="row justify-content-center">
                        <div class="col-lg-2">
                            <label>Name :</label>
                        </div>
                        <div class="col-lg-5">
                            <input type="text" class="form-control" name="txtname" id="txtname" />
                        </div>
                    </div>
                    <div class="x_content"></div>
                    <div class="row justify-content-center">
                        <div class="col-lg-2">
                            <label>Short name :</label>
                        </div>
                        <div class="col-lg-5">
                            <input type="text" class="form-control" name="txtShname" id="txtShname" />
                        </div>
                    </div>
                    <div class="x_content"></div>
                    <div class="row justify-content-center">
                        <div class="col-lg-2">
                            <label>Order :</label>
                        </div>
                        <div class="col-lg-5">
                            <input type="text" class="form-control" name="txtorder" id="txtorder"/>
                        </div>
                    </div>
                    <div class="x_content"></div>
                    <div class="row justify-content-center">
                        <div class="col-lg-2">
                            <label>path :</label>
                        </div>
                        <div class="col-lg-5">
                            <input type="text" class="form-control" name="txtpath" id="txtpath" />
                        </div>
                    </div>
                    <div class="x_content"></div>
                    <div class="row justify-content-center">
                        <div class="col-lg-2">
                            <label>sub Module :</label>
                        </div>
                        <div class="col-lg-5">
                            <select id="ddlSubmain" name="ddlSub" class="form-control">
                                <option value="0" selected>--Select--</option>
                            </select>
                        </div>
                    </div>

                </div>
            </div>


        </div>
    </div>

}

ClinicSystem/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ClinicSystem/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>